# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
# Alt+hjkl to navigate panes (no nvim plugin needed)
#bind -n M-h select-pane -L
#bind -n M-j select-pane -D
#bind -n M-k select-pane -U
#bind -n M-l select-pane -R
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'mocha'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'jimeh/tmuxifier'

set -g @plugin 'fcsonline/tmux-thumbs'
set -g @thumbs-position off_left
set -g @thumbs-osc52 0
set -g @thumbs-command 'echo -n {} | xclip -selection clipboard'
set -g @thumbs-upcase-command 'echo -n {} | xclip -selection clipboard && tmux paste-buffer'
set -g @thumbs-fg-color '#11111b'
set -g @thumbs-bg-color '#f5e0dc'
set -g @thumbs-hint-fg-color '#d20f39'
set -g @thumbs-hint-bg-color '#f5e0dc'
set -g @thumbs-regexp-1 'KEY: \S+\s+([^\s;]+);'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# non-plugin options
set -g default-terminal 'tmux-256color'
set -g status-position top
set -s extended-keys on
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g mouse on

# Visual mouse
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# keymaps
# unbind unbind C-b
# set -g prefix C-Sapce

bind -n C-t new-window -c "#{pane_current_path}"
# Swap pane
bind -n 'M-{' swap-pane -U
bind -n 'M-}' swap-pane -D
bind -n M-O next-layout

bind -n S-Up    resize-pane -U 5
bind -n S-Down  resize-pane -D 5
bind -n S-Left  resize-pane -L 5
bind -n S-Right resize-pane -R 5

# Switch window
bind -n C-M-Left  select-window -t -1
bind -n C-M-Right select-window -t +1
# Move window
#bind -n M-Left  swap-window -t -1\; select-window -t -1
#bind -n M-Right swap-window -t +1\; select-window -t +1
