# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
# Alt+hjkl to navigate panes (no nvim plugin needed)
#bind -n M-h select-pane -L
#bind -n M-j select-pane -D
#bind -n M-k select-pane -U
#bind -n M-l select-pane -R
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'mocha'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'jimeh/tmuxifier'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'


# non-plugin options
set -g default-terminal 'tmux-256color'
set -g status-position top
set -s extended-keys on
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g mouse on

# Visual mouse
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# keymaps
# unbind unbind C-b
# set -g prefix C-Sapce

bind -n M-O next-layout

bind -n S-Up    resize-pane -U 5
bind -n S-Down  resize-pane -D 5
bind -n S-Left  resize-pane -L 5
bind -n S-Right resize-pane -R 5

# Move window
bind -n M-S-Left  swap-window -t -1\; select-window -t -1
bind -n M-S-Right swap-window -t +1\; select-window -t +1
