color0 #1e232a
color1 #d4503e
color2 #00e200
color3 #e0dc00
color4 #4a60e0
color5 #d960d6
color6 #5ffdff
color7 #e0e0e0
color8 #808080
color9 #f09590
color10 #60ffa0
color11 #fff520
color12 #bdc0ff
color13 #f5a0f5
color14 #5ffdff
color15 #ffffff
background #1e232a
foreground #f0f0f0
cursor #ffffff
selection_background #b3d7ff
selection_foreground #000000
